### ISSUE TITLE
pga2d.js is not bundled in resources

### ISSUE THREAD

**Issue by kejace** [embeepea/pga2d#2]
It seems the `index.html` is referring to `resources/public/js/compiled/pga2d.js` which is missing.

**Comment by embeepea** [comment]
Oops, sorry. I'll fix when i get home.  :-)

**Comment by embeepea** [comment]
It turns out that figuring out how to bundle resources/public/js/compiled is tricky, because it contains a lot of generated code that would cause master branch commits to affect many more files than were actually changed.  However, I think I came up with an even better solution: I've added a gh-pages branch that makes it possible to view the diagrams that this code implements online, without having to download anything.  You don't even need to clone the repo; you can just view the diagrams at:

[http://embeepea.github.io/pga2d](http://embeepea.github.io/pga2d)

That page has two links, one to each of the diagrams, corresponding to the files src/pga2d/diagram1.cljs and src/pga2d/diagram2.cljs.

If for some reason you want a local copy, you can clone the repo, checkout the "gh-pages" branch, and then open the top-level index.html file in your browser.  The main reason for having your own local copy, however, would be to be able to interact with the diagram by changing the code, in which case you'll need the ClojureScript compiler.  If you want to do that, let me know and I'll explain how to set it up.
